name: RSS feed con Playwright

on:
  schedule:
    - cron: '0 5,13 * * *'  # Due volte al giorno: 05:00 e 13:00 UTC
  workflow_dispatch:

jobs:
  generate_playwright_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Run Castelgomberto feed script
        run: python Castelgomberto_Playwright.py
        
      - name: Run Gambellara feed script
        run: python Gambellara_Playwright.py

      - name: Commit RSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.xml
          git commit -m "Aggiornamento automatico feed Castelgomberto" || echo "Nessuna modifica da salvare"
          git push
