name: RSS feed con Playwright

on:
  schedule:
    - cron: '0 7,13 * * *'  # Esecuzioni alle 07:00 e 13:00 ora italiana
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Genera e pubblica feed per Gambellara
        run: python Gambellara_Playwright.py || echo "⚠️ Errore durante generazione Gambellara, proseguo"

      - name: Genera e pubblica feed per Castelgomberto
        run: python Castelgomberto_Playwright.py || echo "⚠️ Errore durante generazione Castelgomberto, proseguo"

      - name: Commit e push aggiornamenti
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.xml
          git commit -m "Aggiornamento automatico feed RSS" || echo "Nessuna modifica da committare"
          git push || echo "Push non necessario o già aggiornato"
