name: RSS feed con Playwright

on:
  schedule:
    - cron: '0 7,13 * * *'  # Esecuzioni alle 07:00 e 13:00 ora italiana
  workflow_dispatch:

jobs:
  gambellara-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa Playwright e dipendenze
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Genera e pubblica feed per Gambellara
        run: python Gambellara_Playwright.py
      - name: Upload screenshot per debug
        uses: actions/upload-artifact@v3
          with:
    name: screenshot-gambellara
    path: screenshot.png
