name: RSS feed con Playwright

on:
  schedule:
    - cron: '0 5,13 * * *'  # Due volte al giorno: 05:00 e 13:00 UTC
  workflow_dispatch:

jobs:
  generate_playwright_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright

      - name: Install Playwright browsers
        run: playwright install chromium

       # Castelgomberto
      - name: Genera e pubblica feed per Castelgomberto
        run: xvfb-run --auto-servernum -- python Castelgomberto_Playwright.py

      # Gambellara
      - name: Genera e pubblica feed per Gambellara
        run: xvfb-run --auto-servernum -- python Gambellara_Playwright.py

      # Velo d'Astico
      - name: Genera e pubblica feed per Velo d'Astico
        run: xvfb-run --auto-servernum -- python Velo_dAstico_Playwright.py

      # Torrebelvicino
      - name: Genera e pubblica feed per Torrebelvicino
        run: xvfb-run --auto-servernum -- python Torrebelvicino_Playwright.py

        # Cartigliano
      - name: Genera e pubblica feed per Cartigliano
        run: xvfb-run --auto-servernum -- python Cartigliano_Playwright.py

        # Monteviale
      - name: Genera e pubblica feed per Monteviale
        run: xvfb-run --auto-servernum -- python Monteviale_Playwright.py

     # Upload dei feed RSS
      - name: Commit e push feed RSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add *.xml
          git commit -m "Aggiornamento automatico feed RSS" || echo "Nessuna modifica da commettere"
          git push
