name: RSS Feed Generator

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS generation script
        run: |
          python generate_all.py

      - name: Commit and push generated RSS files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update RSS feeds'
          file_pattern: 'feeds/*.xml'
