name: Genera e aggiorna feed RSS

on:
  schedule:
    - cron: '0 6 * * *'  # Ogni giorno alle 6 del mattino UTC
  workflow_dispatch:  # Permette avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installa dipendenze
        run: pip install requests beautifulsoup4 lxml feedgen

      - name: Esegui generazione feed (Altissimo)
        run: python Altissimo.py

      - name: Esegui generazione feed (Malo)
        run: python Malo.py

      - name: Commit e push aggiornamenti
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.xml
          git commit -m "Aggiornamento automatico feed RSS" || echo "Nessuna modifica"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
