name: Aggiorna feed RSS funzionanti

on:
  schedule:
    - cron: '0 4,11 * * *'  # 06:00 e 13:00 ora italiana (UTC+2)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml feedgen
        pip install playwright
        playwright install chromium

    - name: Run script Altissimo
      run: python Altissimo.py || echo "⚠️ Errore feed Altissimo"

    - name: Run script Malo
      run: python Malo.py || echo "⚠️ Errore feed Malo"

    - name: Run script Arzignano
      run: python Arzignano.py || echo "⚠️ Errore feed Arzignano"

    - name: Run script Barbarano Mossano
      run: python Barbarano.py || echo "⚠️ Errore feed Barbarano"

    - name: Run script Breganze
      run: python Breganze.py || echo "⚠️ Errore feed Breganze"

    - name: Run script Tezze
      run: python Tezze.py || echo "⚠️ Errore feed Tezze"

    - name: Run script Schiavon
      run: python Schiavon.py || echo "⚠️ Errore feed Schiavon"

       - name: Commit e push aggiornamenti
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add *.xml || echo "Nessun file XML da aggiungere"
        git commit -m "Aggiornamento automatico feed RSS" || echo "Nessuna modifica da committare"
        git push || echo "Push non necessario o già effettuato"
