name: Generate RSS Feeds
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4 feedgenerator
          playwright install chromium
          
      - name: Generate feeds
        run: python generate_all.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add feeds/*.xml
          git commit -m "Update feeds[skip ci]" || echo "No changes to commit"
          git push
